dbt-civis:
  target: "{{ env_var('DBT_TARGET') }}"
  default: redshift_adapter
  outputs:
    local_duckdb:
      type: duckdb
      path: "jaffle_shop.duckdb"
      threads: 24
    redshift_adapter:
      type: "{{ env_var('DATABASE_TYPE') }}"
      host: "{{ env_var('DATABASE_HOST') }}"
      port: "{{ env_var('DATABASE_PORT') | as_number }}"
      user: "{{ env_var('DATABASE_USERNAME') }}"
      pass: "{{ env_var('DBT_ENV_SECRET_DATABASE_PASSWORD') }}"
      dbname: "{{ env_var('DATABASE_NAME') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 4
    civis_bigquery:
      type: "{{ env_var('DATABASE_TYPE') }}"
      method: "{{ env_var('GCP_AUTH_METHOD') }}"
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      keyfile: "{{ env_var('DBT_ENV_SECRET_DATABASE_PASSWORD') }}"
      # keyfile: "{{ env_var('GCP_SERVICE_ACCOUNT_KEYFILE_JSON') }}"
      threads: 4
