dbt-civis:
  target: "{{ env_var('DBT_TARGET') }}"
  default: redshift_adapter
  outputs:
    local_duckdb:
      type: duckdb
      path: "jaffle_shop.duckdb"
      threads: 24
    redshift_adapter:
      type: "{{ env_var('ADAPTER_TYPE') }}"
      host: "{{ env_var('DATABASE_HOST') }}"
      port: "{{ env_var('DATABASE_PORT') | as_number }}"
      user: "{{ env_var('DATABASE_USERNAME') }}"
      pass: "{{ env_var('DATABASE_PASSWORD') }}"
      dbname: "{{ env_var('DATABASE_NAME') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 4
